# Generated by Django 6.0.5 on 2026-05-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Route Name (like as 'Dallas to Houston')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Route Details', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ONGOING', 'Ongoing'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel')], default='DRAFT', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CreateRoutes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('start_location_name', models.CharField(blank=True, help_text='Start Location Name', max_length=255)),
                ('start_latitude', models.FloatField(help_text='Start location - Latitude')),
                ('start_longitude', models.FloatField(help_text='Start location - Longitude')),
                ('end_location_name', models.CharField(blank=True, help_text='End Location Name', max_length=255)),
                ('end_latitude', models.FloatField(help_text='End location - Latitude')),
                ('end_longitude', models.FloatField(help_text='End location - Longitude')),
                ('total_distance', models.FloatField(default=0, help_text='Total Distance (km)')),
                ('source_file', models.FileField(blank=True, help_text='Imported File (PDF/Image)', null=True, upload_to='route_imports/%Y/%m/%d/')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='navigation.createroute')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="রুটের নাম (যেমন: 'Dallas to Houston')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='রুটের বিবরণ', null=True)),
                ('start_latitude', models.FloatField(help_text='শুরুর অবস্থান - Latitude')),
                ('start_longitude', models.FloatField(help_text='শুরুর অবস্থান - Longitude')),
                ('start_location_name', models.CharField(blank=True, help_text='শুরুর লোকেশনের নাম', max_length=255)),
                ('end_latitude', models.FloatField(help_text='শেষের অবস্থান - Latitude')),
                ('end_longitude', models.FloatField(help_text='শেষের অবস্থান - Longitude')),
                ('end_location_name', models.CharField(blank=True, help_text='শেষের লোকেশনের নাম', max_length=255)),
                ('total_distance', models.FloatField(default=0, help_text='মোট দূরত্ব (km)')),
                ('waypoint_count', models.IntegerField(default=0, help_text='মোট ওয়েপয়েন্ট সংখ্যা')),
                ('source_file', models.FileField(blank=True, help_text='ইমপোর্টেড ফাইল (PDF/Image)', null=True, upload_to='route_imports/%Y/%m/%d/')),
                ('is_completed', models.BooleanField(default=False, help_text='রুট সম্পূর্ণ হয়েছে কি না')),
                ('is_favorite', models.BooleanField(default=False, help_text='প্রিয় রুট চিহ্নিত')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='সর্বশেষ আপডেটের সময়')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='যাত্রা শুরুর সময়')),
                ('completed_at', models.DateTimeField(blank=True, help_text='যাত্রা শেষের সময়', null=True)),
                ('total_time_spent', models.DurationField(blank=True, help_text='মোট সময় ব্যয়', null=True)),
                ('total_distance_traveled', models.FloatField(default=0, help_text='প্রকৃত ভ্রমণ দূরত্ব (km)')),
                ('status', models.CharField(choices=[('in_progress', 'যাত্রা চলছে'), ('completed', 'সম্পূর্ণ'), ('paused', 'বিরাম'), ('cancelled', 'বাতিল')], default='in_progress', help_text='যাত্রার স্থিতি', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='যাত্রার নোট', null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='navigation.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Route Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text="Waypoints Name (like as: 'Exit 340')", max_length=255)),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('description', models.TextField(blank=True, help_text='ওয়েপয়েন্টের বিবরণ', null=True)),
                ('distance_from_previous', models.FloatField(default=0)),
                ('estimated_time_minutes', models.IntegerField(default=0)),
                ('icon', models.CharField(default='📍', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='navigation.addpermit')),
            ],
            options={
                'ordering': ['permit', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='addpermit',
            index=models.Index(fields=['route', 'order'], name='navigation__route_i_36da44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addpermit',
            unique_together={('route', 'order')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', '-created_at'], name='navigation__user_id_6a272f_idx'),
        ),
        migrations.AddIndex(
            model_name='routehistory',
            index=models.Index(fields=['user', '-started_at'], name='navigation__user_id_52274d_idx'),
        ),
        migrations.AddIndex(
            model_name='waypoint',
            index=models.Index(fields=['permit', 'order'], name='navigation__permit__d8c1f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waypoint',
            unique_together={('permit', 'order')},
        ),
    ]
