# Generated by Django 6.0.5 on 2026-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpermit',
            old_name='source_file',
            new_name='permit_file',
        ),
    ]
