# Generated by Django 6.0.5 on 2026-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_rename_source_file_addpermit_permit_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='description',
            field=models.TextField(blank=True, help_text='Waypoint Details', null=True),
        ),
    ]
