# Generated by Django 6.0.5 on 2026-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_waypoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpermit',
            name='name',
            field=models.CharField(blank=True, help_text="Permits Name (like as: 'Exit 340')", max_length=255, null=True),
        ),
    ]
