# Generated by Django 6.0.5 on 2026-05-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_addpermit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='distance_from_previous',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='estimated_time_minutes',
        ),
    ]
