# Generated by Django 6.0.5 on 2026-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_waypoint_distance_from_previous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createroute',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('START', 'Start'), ('STOP', 'Stop'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel')], default='DRAFT', max_length=20),
        ),
    ]
