services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_wifi_backend

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8002
      --workers 3
      --threads 2
      --timeout 120
      "

    volumes:
      - .:/app

    ports:
      - "8002:8002"

    env_file:
      - .env

    restart: always
  